---
# Source: bdd-gh-1594644088/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bdd-gh-1594644088-bdd-gh-1594644088
  labels:
    draft: draft-app
    chart: "bdd-gh-1594644088-0.0.2"
spec:
  selector:
    matchLabels:
      app: bdd-gh-1594644088-bdd-gh-1594644088
  replicas: 1
  template:
    metadata:
      labels:
        draft: draft-app
        app: bdd-gh-1594644088-bdd-gh-1594644088
    spec:
      containers:
      - name: bdd-gh-1594644088
        image: "gcr.io/jenkins-x-labs-bdd/bdd-gh-1594644088:0.0.2"
        imagePullPolicy: IfNotPresent
        env:
        envFrom:
          null
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 80m
              memory: 128Mi
      terminationGracePeriodSeconds:
